import { useMemo, useState } from 'react'
import type { CompareResult, DebateMessage, Defect, Diagnosis, Product, Taxonomy } from '../../contracts/types'
import { ApiFailure, buildCreateProductRequest, createDebate, createProduct, getCompare, getDiagnosis, getTaxonomy, isMock, streamDebate } from './api'

type View = 'intake' | 'evidence' | 'diagnosis' | 'debate'
const pct = (n: number) => `${Math.round(n * 100)}%`
const label = (s: string) => s.replaceAll('_', ' ')
const simulatorBase = import.meta.env.VITE_SIMULATOR_URL?.trim().replace(/\/$/, '')

const simulatorHref = (compare: CompareResult) => {
  if (!simulatorBase) return undefined
  const params = new URLSearchParams({ before: compare.a.product_ref, after: compare.b.product_ref, cluster: compare.cluster_id })
  return `${simulatorBase}/?${params}`
}

export default function App() {
  const [view, setView] = useState<View>('intake'), [mode, setMode] = useState<'url' | 'manual_prototype'>('url')
  const [input, setInput] = useState('https://www.cabinzero.com/products/classic-36l'), [product, setProduct] = useState<Product | null>(null)
  const [category, setCategory] = useState('travel backpack'), [brand, setBrand] = useState(''), [displayName, setDisplayName] = useState(''), [taxonomy, setTaxonomy] = useState<Taxonomy | null>(null)
  const [diagnosis, setDiagnosis] = useState<Diagnosis | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const [focus, setFocus] = useState<string | undefined>(), [sessionId, setSessionId] = useState(''), [messages, setMessages] = useState<DebateMessage[]>([])
  const [draft, setDraft] = useState('我的背包明明很舒適，你們的分析有問題'), [streaming, setStreaming] = useState(false), [compare, setCompare] = useState<CompareResult | null>(null), [progress, setProgress] = useState('')
  const ref = product?.ref ?? `${product?.product_id}@v${product?.version}`
  const labels = useMemo(() => new Map(taxonomy?.attributes.map(item => [item.id, item.label]) ?? []), [taxonomy])
  const fieldLabel = (id: string) => labels.get(id) ?? label(id)

  const analyze = async () => { try { setBusy(true); setError(''); const body = buildCreateProductRequest({ mode, value: input, category, brand, displayName }); const item = await createProduct(body); const resolvedCategory = item.category ?? category; const fields = await getTaxonomy(resolvedCategory); setProduct(item); setCategory(resolvedCategory); setTaxonomy(fields); setView('evidence') } catch (e) { const blocked = e instanceof ApiFailure && (e.code === 'page_not_extractable' || e.code === 'fetch_failed' || (e.code === 'bad_request' && /page\/raw text too short/i.test(e.message))); if (blocked && mode === 'url') { setMode('manual_prototype'); setInput(''); setError(e.hint ?? 'This page did not provide enough readable product text. Paste its product description below instead — if an AI crawler cannot read a page, it cannot recommend the product.'); } else setError(e instanceof Error ? e.message : 'Could not analyze this product.') } finally { setBusy(false) } }
  const loadDiagnosis = async () => { if (!ref) return; try { setBusy(true); setError(''); for (let i = 0; i < 40; i++) { const result = await getDiagnosis(ref); if (result.data) { setDiagnosis(result.data); setView('diagnosis'); return } await new Promise(r => setTimeout(r, 3000)) } throw new Error('Diagnosis is still running. Please retry in a moment.') } catch (e) { setError(e instanceof Error ? e.message : 'Diagnosis failed.') } finally { setBusy(false) } }
  const beginDebate = async (defect?: Defect) => { if (!ref) return; try { setBusy(true); const session = await createDebate(ref, defect?.defect_id); setFocus(defect?.headline); setSessionId(session.session_id); setMessages(session.messages); setCompare(null); setView('debate') } catch (e) { setError(e instanceof Error ? e.message : 'Could not start debate.') } finally { setBusy(false) } }
  const send = async () => { if (!draft.trim() || streaming) return; const user = { role: 'user' as const, text: draft, ts: new Date().toISOString() }; setMessages(m => [...m, user, { role: 'assistant', text: '', ts: new Date().toISOString() }]); setDraft(''); setStreaming(true); setError(''); try { await streamDebate(sessionId, user.text, token => setMessages(m => { const next = [...m]; next[next.length - 1] = { ...next[next.length - 1], text: next[next.length - 1].text + token }; return next }), async action => { setProgress('Rewriting product evidence → v2 created → re-running comparison…'); if (!action.compare_url) return; for (let i = 0; i < 40; i++) { const result = await getCompare(action.compare_url); if (result.data) { setCompare(result.data); setProgress('Comparison complete'); return } await new Promise(r => setTimeout(r, 3000)) } }) } catch (e) { setError(e instanceof Error ? e.message : 'Debate failed.') } finally { setStreaming(false) } }
  return <main className="shell"><aside className="sidebar"><a className="brand" href="#" onClick={e => { e.preventDefault(); setView('intake') }}><span className="brand-mark">S</span>Signal Audit</a><p className="workspace">WORKSPACE</p><nav><button className={view === 'intake' ? 'nav-item active' : 'nav-item'} onClick={() => setView('intake')}>＋ Add product</button><button className={view === 'diagnosis' ? 'nav-item active' : 'nav-item'} disabled={!diagnosis} onClick={() => setView('diagnosis')}>◈ Diagnosis</button><button className={view === 'debate' ? 'nav-item active' : 'nav-item'} disabled={!sessionId} onClick={() => setView('debate')}>◌ Debate</button></nav></aside><section className="content">{error && <div className="error"><b>Something needs attention.</b> {error}<button onClick={() => setError('')}>×</button></div>}
    {view === 'intake' && <><header className="page-heading"><div><p className="eyebrow">PRODUCT EVIDENCE AUDIT</p><h1>Find what AI cannot see.</h1><p>Analyze any public product URL or pasted product description.</p></div><span className="stage">01 · INTAKE</span></header><section className="intake-card"><div className="toggle"><button className={mode === 'url' ? 'selected' : ''} onClick={() => setMode('url')}>Product URL</button><button className={mode === 'manual_prototype' ? 'selected' : ''} onClick={() => setMode('manual_prototype')}>Product description</button></div><div className="metadata"><label>Product category<input value={category} onChange={e => setCategory(e.target.value)} placeholder="e.g. running shoes, skincare, headphones" /></label>{mode === 'manual_prototype' && <><label>Brand<input value={brand} onChange={e => setBrand(e.target.value)} placeholder="Required for pasted text" /></label><label>Product name<input value={displayName} onChange={e => setDisplayName(e.target.value)} placeholder="Optional" /></label></>}</div><label>{mode === 'url' ? 'Link to a public product page' : 'Paste your product description'}</label>{mode === 'url' ? <input value={input} onChange={e => setInput(e.target.value)} /> : <textarea value={input} onChange={e => setInput(e.target.value)} placeholder="Paste the product page copy, specs, materials, dimensions and customer proof…" />}{mode === 'manual_prototype' && <p className="manual-note">Tip: copy the product description, specification table, FAQ and review claims from the original page. This is the evidence an AI needs to make a recommendation.</p>}<div className="intake-actions"><p>{isMock ? 'Demo mode uses CabinZero fixture data. Set VITE_API_BASE to analyze arbitrary products.' : 'Fields and labels adapt to the category you enter; we only use evidence stated on the supplied page.'}</p><button className="primary" onClick={analyze} disabled={busy || !input.trim() || (mode === 'manual_prototype' && !brand.trim())}>{busy ? 'Extracting attributes…' : 'Analyze product →'}</button></div></section></>}
    {view === 'evidence' && product && <><Header product={product} stage="02 · EVIDENCE" /><section className="attributes full"><div className="attribute-heading"><div><p className="eyebrow">EXTRACTED PRODUCT EVIDENCE · {taxonomy?.category ?? category}</p><h2>What the page actually states</h2><p>Grey question marks are claims an AI cannot verify from the source.</p></div><button className="primary" onClick={loadDiagnosis} disabled={busy}>{busy ? 'Building diagnosis…' : 'Continue to diagnosis →'}</button></div><Attributes product={product} fieldLabel={fieldLabel} /></section></>}
    {view === 'diagnosis' && diagnosis && <><Header product={product!} stage="03 · DIAGNOSIS" /><section className="score-grid"><article className="score-card main-score"><p>Recommendation share</p><strong>{pct(diagnosis.overall.recommendation_share)}</strong><span>across {diagnosis.overall.n_simulations} simulations</span></article><article className="score-card"><p>Considered by AI</p><strong className="plain-score">{pct(diagnosis.overall.consideration_share)}</strong><div className="bar"><span style={{ width: pct(diagnosis.overall.consideration_share) }} /></div></article><article className="score-card"><p>Retrieval rate</p><strong className="plain-score">{pct(diagnosis.overall.retrieved_rate ?? 0)}</strong><div className="bar"><span style={{ width: pct(diagnosis.overall.retrieved_rate ?? 0) }} /></div></article></section><ComparedProducts products={diagnosis.overall.vs} /><section className="section-title"><div><p className="eyebrow">EVIDENCE GAPS</p><h2>Why recommendations are being lost</h2><p>{diagnosis.exec_summary}</p></div><span className="count">{diagnosis.defects.length} findings</span></section><section className="defect-list">{diagnosis.defects.map(d => <DefectCard key={d.defect_id} defect={d} fieldLabel={fieldLabel} onDiscuss={() => beginDebate(d)} />)}</section></>}
    {view === 'debate' && <><header className="page-heading"><div><p className="eyebrow">EVIDENCE DEBATE</p><h1>Challenge the diagnosis.</h1><p>{focus ?? 'Give the agent concrete product evidence it may be missing.'}</p></div><span className="stage">04 · DEBATE</span></header><section className="chat">{messages.length === 0 && <div className="empty-chat">Ask why this product is losing — then add a concrete fact that was missing from its page.</div>}{messages.map((m, i) => <article className={`bubble ${m.role}`} key={i}><small>{m.role === 'user' ? 'YOU' : 'SIGNAL AUDIT'}</small>{m.text ? <MarkdownMessage text={m.text} /> : <p><span className="cursor">▍</span></p>}</article>)}{progress && <div className="progress-card"><span className="dot" /> {progress}</div>}{compare && <Compare compare={compare} />}</section><div className="composer"><textarea value={draft} onChange={e => setDraft(e.target.value)} disabled={streaming} placeholder="Explain what the product page is missing…" /><button className="primary" onClick={send} disabled={streaming || !draft.trim()}>{streaming ? 'Analyzing…' : 'Send →'}</button></div></>}
  </section></main>
}
function Header({ product, stage }: { product: Product; stage: string }) { return <header className="product-header"><div><p className="eyebrow">{stage} · {product.ref ?? `${product.product_id}@v${product.version}`}</p><h1>{product.display_name}</h1>{product.source_url && <a href={product.source_url} target="_blank" rel="noreferrer">{product.source_url.replace('https://', '')} ↗</a>}</div><span className="stage">{stage}</span></header> }
function Attributes({ product, fieldLabel }: { product: Product; fieldLabel: (id: string) => string }) { return <div className="attribute-table">{product.attributes.map(a => <div className={a.value ? 'attribute-row' : 'attribute-row unknown'} key={a.attribute_id}><span>{fieldLabel(a.attribute_id)}</span><b>{a.value ?? '? Not found on page'}</b><small>{a.evidence ?? 'No supporting text was extracted.'}</small></div>)}</div> }
function ComparedProducts({ products }: { products: Record<string, number> }) {
  const entries = Object.entries(products)
  return <section className="compared-products"><div><p className="eyebrow">COMPARISON SET</p><h2>Compared with</h2><p>Only products actually used in this diagnosis are listed.</p></div><div className="compared-product-list">{entries.length ? entries.map(([ref, share]) => <article key={ref}><code>{ref}</code><strong>{pct(share)}</strong><span>recommendation share</span></article>) : <p>No eligible same-category competitors were available for this diagnosis.</p>}</div></section>
}
function MarkdownMessage({ text }: { text: string }) {
  const blocks = text.split(/\n{2,}/)
  return <div className="markdown-message">{blocks.map((block, index) => {
    const lines = block.split('\n')
    if (lines.every(line => /^[-*]\s+/.test(line))) return <ul key={index}>{lines.map((line, lineIndex) => <li key={lineIndex}>{inlineMarkdown(line.replace(/^[-*]\s+/, ''))}</li>)}</ul>
    return <p key={index}>{lines.map((line, lineIndex) => <span key={lineIndex}>{lineIndex > 0 && <br />}{inlineMarkdown(line)}</span>)}</p>
  })}</div>
}
function inlineMarkdown(text: string) {
  const parts = text.split(/(`[^`]+`|\*\*[^*]+\*\*|\*[^*]+\*|\[[^\]]+\]\([^\s)]+\))/g)
  return parts.map((part, index) => {
    if (part.startsWith('**') && part.endsWith('**')) return <strong key={index}>{part.slice(2, -2)}</strong>
    if (part.startsWith('*') && part.endsWith('*')) return <em key={index}>{part.slice(1, -1)}</em>
    if (part.startsWith('`') && part.endsWith('`')) return <code key={index}>{part.slice(1, -1)}</code>
    const link = part.match(/^\[([^\]]+)\]\(([^\s)]+)\)$/)
    if (link) return <a key={index} href={link[2]} target="_blank" rel="noreferrer">{link[1]}</a>
    return part
  })
}
function ContentPatch({ text }: { text: string }) {
  const json = parseJsonBlock(text)
  if (json !== null) return <details className="json-patch"><summary>View ready-to-paste JSON-LD</summary><pre>{JSON.stringify(json, null, 2)}</pre></details>
  return <section className="content-patch"><p className="eyebrow">READY-TO-PASTE COPY</p><MarkdownMessage text={text} /></section>
}
function parseJsonBlock(text: string): unknown | null {
  const candidate = text.trim().replace(/^```(?:json|jsonld)?\s*/i, '').replace(/\s*```$/, '')
  if (!(candidate.startsWith('{') || candidate.startsWith('['))) return null
  try { return JSON.parse(candidate) } catch { return null }
}
function DefectCard({ defect, fieldLabel, onDiscuss }: { defect: Defect; fieldLabel: (id: string) => string; onDiscuss: () => void }) { return <article className="defect-card"><div className="defect-top"><span className={`severity ${defect.severity}`}>{defect.severity}</span><span className={`gap ${defect.gap ?? 'unclear'}`}>{label(defect.gap ?? 'unclear')}</span><span className="attribute">{fieldLabel(defect.attribute_id)}</span><span className="loss">{pct(defect.evidence.losing_share_in_cluster)} · {defect.evidence.cluster_id}</span></div><h3>{defect.headline}</h3><div className="defect-columns"><blockquote>{defect.evidence.sample_rejection_reasons[0] ? `“${defect.evidence.sample_rejection_reasons[0]}”` : 'No sample rejection reason recorded.'}</blockquote><p><b>Competitor evidence</b>{defect.evidence.competitor_contrast || 'No competitor evidence recorded.'}</p></div>{defect.why_it_happens && <section className="why-it-happens"><p className="eyebrow">WHY IT HAPPENS</p><MarkdownMessage text={defect.why_it_happens} /></section>}<footer><p><b>Suggested fix</b>{defect.suggested_fix}</p><button className="discuss" onClick={onDiscuss}>Discuss this →</button></footer>{defect.content_patch && <ContentPatch text={defect.content_patch} />}</article> }
function Compare({ compare }: { compare: CompareResult }) { const href = simulatorHref(compare); return <section className="compare"><p className="eyebrow">EVIDENCE IMPACT · {compare.cluster_id}</p><h2>{pct(compare.a.recommendation_share)} <span>→</span> {pct(compare.b.recommendation_share)}</h2><strong>+{pct(compare.delta_recommendation)} recommendation share</strong><ul>{compare.changes_applied.map((c, i) => <li key={i}>{c}</li>)}</ul>{href && <a className="simulator-link" href={href}>Open the before / after simulator →</a>}</section> }
